

spring:
  datasource:
    username: scott
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
  jackson:
    date-format: yyyy-MM-dd # 返回json时自动格式化日期


  resources:
      static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/ # 静态资源访问路径
  thymeleaf:
        # suffix: .html
        cache: false
        mode: HTML5
        # encoding: UTF-8
        # prefix: classpath:/templates/